files=( /usr/lib/node_modules/npm/lib/package-url-cmd.js
/usr/lib/node_modules/npm/lib/utils/format-search-stream.js
/usr/lib/node_modules/npm/lib/utils/open-url-prompt.js
/usr/lib/node_modules/npm/lib/workspaces/update-workspaces.js
/usr/lib/node_modules/npm/node_modules/@colors/colors/LICENSE
/usr/lib/node_modules/npm/node_modules/@colors/colors/examples/normal-usage.js
/usr/lib/node_modules/npm/node_modules/@colors/colors/examples/safe-string.js
/usr/lib/node_modules/npm/node_modules/@colors/colors/index.d.ts
/usr/lib/node_modules/npm/node_modules/@colors/colors/lib/colors.js
/usr/lib/node_modules/npm/node_modules/@colors/colors/lib/custom/trap.js
/usr/lib/node_modules/npm/node_modules/@colors/colors/lib/custom/zalgo.js
/usr/lib/node_modules/npm/node_modules/@colors/colors/lib/extendStringPrototype.js
/usr/lib/node_modules/npm/node_modules/@colors/colors/lib/index.js
/usr/lib/node_modules/npm/node_modules/@colors/colors/lib/maps/america.js
/usr/lib/node_modules/npm/node_modules/@colors/colors/lib/maps/rainbow.js
/usr/lib/node_modules/npm/node_modules/@colors/colors/lib/maps/random.js
/usr/lib/node_modules/npm/node_modules/@colors/colors/lib/maps/zebra.js
/usr/lib/node_modules/npm/node_modules/@colors/colors/lib/styles.js
/usr/lib/node_modules/npm/node_modules/@colors/colors/lib/system/has-flag.js
/usr/lib/node_modules/npm/node_modules/@colors/colors/lib/system/supports-colors.js
/usr/lib/node_modules/npm/node_modules/@colors/colors/package.json
/usr/lib/node_modules/npm/node_modules/@colors/colors/safe.d.ts
/usr/lib/node_modules/npm/node_modules/@colors/colors/safe.js
/usr/lib/node_modules/npm/node_modules/@colors/colors/themes/generic-logging.js
/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/override-resolves.js
/usr/lib/node_modules/npm/node_modules/@npmcli/disparity-colors/lib/index.js
/usr/lib/node_modules/npm/node_modules/@npmcli/fs/lib/common/owner-sync.js
/usr/lib/node_modules/npm/node_modules/@npmcli/fs/lib/with-owner-sync.js
/usr/lib/node_modules/npm/node_modules/@npmcli/fs/lib/with-owner.js
/usr/lib/node_modules/npm/node_modules/@npmcli/move-file/lib/index.js
/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js
/usr/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/escape.js
/usr/lib/node_modules/npm/node_modules/builtins/index.js
/usr/lib/node_modules/npm/node_modules/cli-table3/src/debug.js
/usr/lib/node_modules/npm/node_modules/cmd-shim/lib/index.js
/usr/lib/node_modules/npm/node_modules/ignore-walk/lib/index.js
/usr/lib/node_modules/npm/node_modules/ini/lib/ini.js
/usr/lib/node_modules/npm/node_modules/just-diff-apply/index.d.ts
/usr/lib/node_modules/npm/node_modules/just-diff-apply/index.tests.ts
/usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/dns.js
/usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/pipeline.js
/usr/lib/node_modules/npm/node_modules/minimatch/lib/path.js
/usr/lib/node_modules/npm/node_modules/npm-install-checks/lib/index.js
/usr/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/clean-url.js
/usr/lib/node_modules/npm/node_modules/read-cmd-shim/lib/index.js
/usr/lib/node_modules/npm/node_modules/rimraf/node_modules/brace-expansion/LICENSE
/usr/lib/node_modules/npm/node_modules/rimraf/node_modules/brace-expansion/index.js
/usr/lib/node_modules/npm/node_modules/rimraf/node_modules/brace-expansion/package.json
/usr/lib/node_modules/npm/node_modules/rimraf/node_modules/glob/LICENSE
/usr/lib/node_modules/npm/node_modules/rimraf/node_modules/glob/common.js
/usr/lib/node_modules/npm/node_modules/rimraf/node_modules/glob/glob.js
/usr/lib/node_modules/npm/node_modules/rimraf/node_modules/glob/package.json
/usr/lib/node_modules/npm/node_modules/rimraf/node_modules/glob/sync.js
/usr/lib/node_modules/npm/node_modules/rimraf/node_modules/minimatch/LICENSE
/usr/lib/node_modules/npm/node_modules/rimraf/node_modules/minimatch/minimatch.js
/usr/lib/node_modules/npm/node_modules/rimraf/node_modules/minimatch/package.json
/usr/lib/node_modules/npm/node_modules/ssri/lib/index.js
/usr/lib/node_modules/npm/node_modules/treeverse/lib/index.js
/usr/lib/node_modules/npm/node_modules/validate-npm-package-name/lib/index.js )

for el in "${files[@]}"
do
    newName=$el"_1"
    sudo rm -v $newName
done
